### ISSUE TITLE
Assignment One is Ready for Grading

### ISSUE THREAD

**Issue by arielxhbi** [SES-5215-F2020/xiaohebi-quant#1]
Please see documents named "assignment 1 final". Thank you, and I look forward to your feedback!

**Comment by c-voulgaris** [comment]
Well done!

**Comments on your code**
Here are some suggested edits you could make to your markdown file to make your submission easier to read:

Line 9: If you add a comma after the r, and then include the option message-FALSE, that will prevent your knitted output from including the package loading messages that add clutter to the first part of your html file.

Line 27: Add a space after the period so that your numbered list is formatted as a list in your html file.

Line 33: Add a comma after the r so that the results='hide' option works.

Lines 48 - 52: No need to show both the formatted and unformatted versions of the table. I suggest deleting these lines.

**Comments on your content**
Based on the types of questions you describe being interested in, you might want to consider filtering your sample further to include only adults, or perhaps even only adults who are employed.
