### ISSUE TITLE
assignment 2 submitted

### ISSUE THREAD

**Issue by arielxhbi** [SES-5215-F2020/xiaohebi-quant#2]
Assignment 2 is ready for grading (file name: assignment 2 for submission). Thank you so much!

**Comment by saratepfer** [comment]
Thank you, Ariel! Nice job. Side note: You do not need to assign Catherine to the assignments, as she will not be grading. Please see a few comments on code and content, below: 

**Comments on Code**
- Line 8: Replace "results = "hide"" with "message = FALSE" to prevent R from printing additional messages when you load your packages.
- Lines 59-76: Rather than calculating the 95% confidence interval by hand, you can use the t.test() function for each variable, which will output each variable's 95% CI.
- Line 100: Add "message = FALSE" to prevent R from printing additional messages when you load your packages.

**Comments on Content**
- You mention that your population is the population of Massachusetts; however, you then filter for people over the age of 18. I would also state this explicitly when you describe your population.
- For your proportions and 95% CIs for the categorical variables, it would be helpful if the tables you produced identified which categories the estimates and CIs correspond to. As you currently have it, you kind of have to read between the two tables to figure that out. It would be helpful to produce a single table with labels/values. Please see Catherine's example assignment or come by office hours/schedule an appointment to discuss how to do this.
