### ISSUE TITLE
Assignment 3 ready for grading

### ISSUE THREAD

**Issue by arielxhbi** [SES-5215-F2020/xiaohebi-quant#3]
Assignment 3 is ready for grading. Thank you so much!

**Comment by saratepfer** [comment]
Nice job, Ariel! Please see a few comments below: 

- Rather than producing a separate table (line 37), I think it is more interesting to compare the expected and observed tables from the chi square test results. This will tell you where the strongest differences were between the expected and observed values across all categories.
- When you perform a Pearson's correlation test, you can check for both significance _and_ strength. It is important to comment on both. In your case, the strength of the correlation is fairly weak (-0.08)
- Regarding presentation: your knitted html file might read a bit more easily if you placed headings between the different types of tests. As it is currently, the whole report kind of bleeds together rather than having distinct sections.
